spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hovet_queue"
    username: "root"
    password: "1234"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  servlet:
    context-path: '/api'